export const packagesDetail = [
  {
    id: 1,
    title: "Website Basic",
    price: "40",
    p1: "Full stack web development (MERN)",
    p2: "1 landing page ($40)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (220$)",
    p5: "6 landing page delivery in 20 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 2,
    title: "Website Basic",
    price: "30",
    p1: "Simple Tamplate in React.Js",
    p2: "1 landing page ($30)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (150$)",
    p5: "6 landing page delivery in 10 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 3,
    title: "Website Basic",
    price: "25",
    p1: "PSD, Figma, XD, PNG, JPG to React.Js",
    p2: "1 landing page ($25)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (120$)",
    p5: "6 landing page delivery in 10 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 4,
    title: "Website Basic",
    price: "15",
    p1: "Simple Tamplate in HTML, CSS",
    p2: "1 landing page ($30)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (70$)",
    p5: "6 landing page delivery in 10 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 5,
    title: "Website Basic",
    price: "20",
    p1: "PSD, Figma, XD to HTML and Bootstrap",
    p2: "1 landing page ($20)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (100$)",
    p5: "6 landing page delivery in 10 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 6,
    title: "Website Basic",
    price: "20",
    p1: "Bootstrap and React Bootstrap",
    p2: "1 landing page ($20)",
    p3: "1 Landing page delivery in 2 days",
    p4: "Free offer 6 page in only (100$)",
    p5: "6 landing page delivery in 10 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 7,
    title: "Website Basic",
    price: "10",
    p1: "Navbar , Menubar , Sidebar, Hamburger",
    p2: "1 component ($10)",
    p3: "1 component delivery in 1 days",
    p4: "Free offer 3 component in only (20$)",
    p5: "3 component delivery in 3 working days",
    p6: "Unlimited revision until you are satisfied",
    p7: "Free support 24/7",
  },
  {
    id: 7,
    title: "Amazon Dropshipping",
    price: "05",
    p1: "Handling, storing, and shipping products",
    p2: "Basic charges only ($5)",
    p3: "Customer orders online",
    p4: "Charges will be depend on your product",
    p5: "Manages the online fulfillment",
    p6: "I will responce 100% you will satisfied",
    p7: "Free support 24/7",
  },
];
