export const packagesDetail = [
  {
    id: 1,
    title: "Website Basic",
    price: "50000",
    p1: "3 Custom Design Concepts",
    p2: "1 Creative Designer",
    p3: "No Templates or Clipart",
    p4: "Five Revisions (Additional 2000)",
    p5: "Delivery in 2-3 Business Days",
    p6: "24 X 7 Support",
  },
  {
    id: 1,
    title: "Website Startup ",
    price: "45000",
    p1: "3 Custom Design Concepts",
    p2: "1 Creative Designer",
    p3: "No Templates or Clipart",
    p4: "Five Revisions (Additional 2000)",
    p5: "Delivery in 2-3 Business Days",
    p6: "24 X 7 Support",
  },
  {
    id: 1,
    title: "Website Unlimited ",
    price: "75000",
    p1: "3 Custom Design Concepts",
    p2: "1 Creative Designer",
    p3: "No Templates or Clipart",
    p4: "Five Revisions (Additional 2000)",
    p5: "Delivery in 2-3 Business Days",
    p6: "24 X 7 Support",
  },
  {
    id: 1,
    title: "Website Unlimited",
    price: "75000",
    p1: "3 Custom Design Concepts",
    p2: "1 Creative Designer",
    p3: "No Templates or Clipart",
    p4: "Five Revisions (Additional 2000)",
    p5: "Delivery in 2-3 Business Days",
    p6: "24 X 7 Support",
  },
];
